apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tom
  template:
    metadata:
      labels:
        app: tom
    spec:
      containers:
      - name: tomcat
        image: 35.238.55.192/cicd/tomcat:1
        ports:
        - name: main
          protocol: TCP
          containerPort: 8080
