apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: 35.185.35.12/stack/tomcat:1
      ports:
        - containerPort: 8080
    
